### ISSUE TITLE
Add support for more image formats

### ISSUE THREAD

**Issue by Accuracy-exe** [acmpesuecc/sizer-imageResizing#3]
Add image formatting support in Server (Server should be able to handle and resize png, jpeg / jpg, gif)
Modify Web app frontend to allow User to select resized image's format by adding a drop down
User should be able to upload image in any valid image format and choose the encoding format for the resized image
examples: *.png • *.jpeg • *.gif

Make sure to stick to the color palette and theme of the web app

**Comment by namrataaravinda** [comment]
can i get this assigned please?

**Comment by Accuracy-exe** [comment]
!assign @namrataaravinda

**Comment by namrataaravinda** [comment]
can i get this assigned once again please?

**Comment by Accuracy-exe** [comment]
!assign @namrataaravinda

**Comment by Aditya-C-S** [comment]
hey can you please assign me this

**Comment by Aditya-C-S** [comment]
@Accuracy-exe can u assign it to me , because no one else is assigned

**Comment by Accuracy-exe** [comment]
!assign @Aditya-C-S

**Comment by Aditya-C-S** [comment]
> !assign @Aditya-C-S

not showing that i am assigned , can i still send pull request

**Comment by Accuracy-exe** [comment]
!assign @Aditya-C-S

**Comment by Accuracy-exe** [comment]
@Aditya-C-S You are assigned to a different issue

**Comment by Aditya-C-S** [comment]
can u just tell me to which am i assigned , i am not able to see it

**Comment by RithishRM** [comment]
Can I get this issue

**Comment by Accuracy-exe** [comment]
!assign @RithishRM 45

**Comment by Accuracy-exe** [comment]
Hey @RithishRM, You are currently assigned to a different issue

**Comment by RithishRM** [comment]
Idt im assigned to anything now.

**Comment by Accuracy-exe** [comment]
!assign @RithishRM

**Comment by Hemz1416** [comment]
can i get assigned?

**Comment by Hemz1416** [comment]
can i get assigned plz?

**Comment by Hemz1416** [comment]
@Accuracy-exe  Can u Assign me?
